about:
  firstName: Yuval
  lastName: Herziger
  nickname: Yuvi
  intro: |
    I'm A software engineer with over 8 years of diverse experience in a variety of fields and engineering paradigms;
    I believe in leading by example and constant learning; a certified AWS Solutions Architect Associate (SAA-C01).
    Off the grid, I'm a proud father, a loving partner to an academic researcher, an amateur landscape
    and portrait photographer, and an okay guitar player.
    Born and raised in Israel, I've been an ex-pat for the past 7 years. I currently live in Columbus, Ohio. I've moved
    to Columbus after having lived for 4 years in Cologne (Köln), Germany.
  contact:
    emailAddress: yuvalhrz@gmail.com
  profiles:
    - name: GitHub
      url: https://www.github.com/yuvalherziger
    - name: LinkedIn
      url: https://www.linkedin.com/in/yuval-herziger-677b1531/
    - name: 500px
      url: https://500px.com/p/yuvalherziger?view=photos
    - name: Facebook
      url: https://www.facebook.com/herziger
  languages:
    - Hebrew  - native
    - English - fluent
    - German  - business proficiency (B2)
    - Spanish - basic
certifications:
  - name: AWS Solutions Architect Associate (SAA-C01)
    credentials: https://certmetrics.com/amazon/public/transcript.aspx?transcript=BFLC3C4C2JQ41J37
    expires: Jan 2023
experience:
  - companyName: Immuta Inc.
    companyWebsite: https://www.immuta.com
    location: Columbus, OH, USA
    roles:
    - name: Lead Software Engineer
      startDate: May 2020
      endDate: Present
      responsibilities:
        - Oversee the Applications and Integrations team
        - Prioritize, plan, and execute ongoing development tasks across several codebases in an agile team
        - Provide deliverables to Immuta customers in the form of custom plugins and integrations
    - name: Software Engineer
      startDate: Aug 2018
      endDate: May 2020
      responsibilities:
        - Member of Immuta's Applied Engineering team
        - Designed and developed an identity manager that supported SAML 2.0 & OAuth 2.0/OIDC
        - Led technical POC’s with enterprise customers (some reaching $1m in ACV)
        - Assisted with HA and FT Kubernetes deployments on various infrastructures, primarily AWS and Azure
        - Developed and maintained various microservices
        - Provided assistance in various customer POC's
        - Worked on a variety of distributed data computation systems such as EMR, Snowflake, and Databricks
        - Developed front-end components using Angular v{6, 7, 10}
  - companyName: Quintly GmbH
    companyWebsite: https://www.quintly.com
    location: Cologne, NRW, Germany
    roles:
    - name: Scrum Master
      startDate: Jan 2017
      endDate: Feb 2018
      responsibilities:
        - Led a team of 3 software engineers
        - Estimated, planned, coordinated, and executed implementation of new features
    - name: Software Engineer
      startDate: Feb 2016
      endDate: Feb 2018
      responsibilities:
        - Implemented new features and maintain Quintly’s social media analytics product in a Scrum team
        - Developed back-end features using PHP
        - Strong Emphasis on Domain-Driven Design (DDD) patterns
        - Developed front-end components using ReactJS and Redux
        - Experimented with Test-Driven Development (TDD) and wrote comprehensive unit and integration tests
        - Worked with MySQL, AWS DynamoDb, and MongoDB databases
        - Studied and consumed from social media REST API's, often more than the docs could offer
  - companyName: Incuda GmbH
    companyWebsite: https://www.incuda.com
    location: Düsseldorf, NRW, Germany
    roles:
      - name: Software Engineer
        startDate: Aug 2014
        endDate: Feb 2016
        responsibilities:
          - Supported data integration projects for e-commerice clients using Pentaho Data Integration (PDI)
          - Specialized in consumption of web analytics and marketing data
          - Integrated a variety of data sources (API's, relational databases, NoSQL databases)
          - Targeted ETL jobs to distributed analytics databases using Java and PDI
          - Developed custom PDI plugins with Java using the PDI API’s for various types of ETL processes
          - Specialized in the deployment and setup of Snowplow, a robust open-source web analytics platform
  - companyName: TVMania Ltd.
    companyWebsite: ""
    location: Herzliya, Israel
    roles:
      - name: Software Engineer
        startDate: Jun 2013
        endDate: Jul 2014
        responsibilities:
          - Developed and maintained a supply-chain management support system using classic ASP, C#.NET, and MSSQL
          - Prototyped a BI architecture using SSIS, SSRS, and SSAS
education:
  - institute: Ruppin Academic Center
    degree: B.Sc. Industrial Engineering & Management
    major: Information Systems
    graduationDate: July 2013
    GPA: 3.3 (87%)
openSource:
  - projectName: Katch
    description: A Python library
    source: https://github.com/python-utils/katch
fakeSkills:
  - name: Add last-minute items to a release
    proficiency: 10
  - name: Spend a day looking for an errant character
    proficiency: 9
  - name: Exit vim
    proficiency: 5
  - name: Restart my computer regularly
    proficiency: 2
  - name: Distinguish between a bug from a feature
    proficiency: 6
  - name: Remember to remove frustration-loaded log calls
    proficiency: 4
  - name: Run kubectl in the wrong kube context
    proficiency: 3
  - name: Roll k8s pods to solve problems
    proficiency: 9
  - name: Embrace 'git push -f' as a lifestyle
    proficiency: 8
skills:
  - name: Python
    proficiency: 9
  - name: Angular
    proficiency: 9
  - name: Go
    proficiency: 7
  - name: Java
    proficiency: 5
  - name: Bash/Linux
    proficiency: 6
  - name: Node.js (JS + TS)
    proficiency: 8
  - name: Docker
    proficiency: 9
  - name: Relational DBs
    proficiency: 9
  - name: NoSQL
    proficiency: 6
  - name: Kubernetes
    proficiency: 8
  - name: Terraform
    proficiency: 4
  - name: AWS Infrastructure
    proficiency: 7
  - name: Azure Infrastructure
    proficiency: 5
  - name: PHP
    proficiency: 6
  - name: React.js
    proficiency: 5
picture: |

  This is ASCII-me:
                         ............'''''''....
              ..  ...'..'''.......'',,;;;::;;,,'''........
              ......,;,',;;,,,,,;;;;cllllooooolll:;;;,'''...
          .....'',,,:cllllooooooooodxxxxxxxxxxdddolc:;;;;,'....
         ....'';c:cloodxxxxkkkkkkkkkkkkkkkkkkkxxxddolc:cc:;,....  .
        ...';,;cllodddxxkkkkkkOOOkOOOOOOOOOOOkkkkxxdolcccc:;,...
       ..',;:ccllloddxxkkkkOOOOOOOO0000000OOOOOkkkxdoollcc:;;'..
       ..;;;:clolooddxxkkOOOO00000000000000000OOkkxxdooolc:;,....
      ..,::;:clooddddxkkOO000KKKKKKKKKKKK000000OOkxxddoooc:;,'..  .
      ..,:::::loddddxxkOO000KKKKKKKKKKKKK000000OOkxxxddoolc:;;'.......
     ...,:::::ldddxxxkkkO00000KKKKKKKKKKKK00000OOkkkxxxddolcc:,.......
      ..';:::cldddxxxkkOOO00000KKKKKKKKK000000OOOkkkkkkxxdollc;'......
   .....';:::coodxxxkkkOOO000000000000000000OOOOOOkkkkkkxdolcc:,......
  .......;::ccoddxxkkkkOO0000000000000000000OOOOOOkkxdddoollcc:;.......
   ......,::cloodxkkkkkkkO000000000000000000000OOkxdlc;,,,,,;:c:,.....
   ......,::cclllollooddxk0000KKKKK00KKKKK0000Okxoc;,,,''....';c;.......
   ......;:::;,,,,,',;::coxkO0KKKKKKKKKKK0kxOko:;,'',:cccc;'..'::'...';.
   . ...';:;,.....'''.'''',;:ldkO00KKKKK0Oxoooc:clldxkkkxxdlc;,,:,. .;c'
  ...  .,::,'..';clodddocc::;;:lxO0000000Okdooolllc::;:cccllooo:;,..'cc.
   .'. .':;,;:clooolc:;;,;cclooodxO000000Oxooolldl'...'c:,;coxxoc;...ll.
   .,,..'::coollc,';;....;ooclodookO0000Okolodoodxc;;;cllccloxxdc;,..cl.
    ;l'.';:ldxolc::ll:;:coddoddoooxkO0OOkxolodxxxxxxxxxxxxxxxxxdl:;'.,;.
   .lo'.';:ldxxddxxxxxxkkkkxxdolodxkOOOOkxdoloddxkkOOOOOOOOOOkkdl:;'.,,.
   .cc..';:ldxkkkOOOkOOOOkkkxdoodddxkkkkkxdooodxkkkOOkkOkkOOkkkxoc,..;,
    ':'.';:ldxkOOOOOOOOkOOOkkxxdoddxxxkOkkddoodkkOOO00OOOOOOkkxdo:'.,:.
    .;:..,;ldxxkkOOOOOOO0000OkoloodxkOOOOkxdolldk000000000OOOkxdl:':l,
     .cc,.,codxxkkOO00000KK0kocloddxO000Okxddolcok0KKK00000OOkxdl;','
     .,lo;';lodxkOO00KKKKKKOdloxkkkk0KKKK0kxxkxdoxO0KKKK000Okxxol;.
       ':,.,:loxkOO0KKKKKK0Oxddddoodk0000kollloooxkO000K000Okxdlc,.
          .';codkkO0000000Okxdollccloddxdlccc:clodddxkkO00Okkxol:'.
          ..,:lodxOOOOkkxxddoclloolodxxxxooolcclccllllooxOOxxdoc;.
           .';cllokkdlllccclc:cclllodxkkxdolllllccc:;;::lxkdool:,.
            .':llldxdlc:;::cccloooooddddddooooolc:::::cllddlllc;..
             .,:lccxkxdollc:;:clooooddddddddoollc;:coddxkOxlloc,.
             .';cc:cxkkkxxdl:;:coooddooodxxxollccldxkkkkkxoclc;..
              .':c:;lxkkkxxxdooodxxkkkxxkkkkxddodxxxkkxxxoccc;'.
               .':c:;ldxxxdxxddddxxkkxxkkxxxxxxxxxkkxxdooc;:;'..
                ..;:;;:looodxxxxddddxxxxxxxxxxxkkkkxxdl:;;;;'.,,.
                 ..,;,,;cllodxxkkkxxxxddxxxkOOOkkxxddl:,,;;'.,::.
                 ...',,,;cloodxkkkkxxxddxxxkkOkkxdool:,,,'..';cc,.
                 .,...'',;cloddddxxxxkkxkkxkkkkxxdlc:,,,''.',:cc:.
                 .,,.....';:cloddxxxkOOkOkkxxxxxdol;,','''',;:ool:.
                 .;;,'.....';clodxxxxxxxxxxxdddol:;'',,''',,;coddl:'.
                 .::;,'''''..,;cloddooooooooolc:;,,,'',,,,,,;ldxxdoc;,...
                .;ll:,'',,,,,'',,;:;;;;::;,,;,'',,,,,;:;;;,,;cdxxxdolc:;;,'.
             ...,codl;'',;::::;;,,''''',''.',,,,;;;:cllc:;,,;:ldxkkxxddlccc;.
          ..'',:loddo:,,;:cc::cllc:::cc::;;;:::::cloooolc:;;;:cloxxxxkxxddo:.
        .,;:::coxxxdl:;;::cllcloooooddoooooollloloxxxxdoolc:::::clooxxkkkxl'
       .cloloodxkkxdc;;::cllloodxxxxkxxxxxxxxddxxxkkkxddddlcccc::cclodxxxd;.
       .lxxddxxxxxdl:::cclooodxxxxkkkkkxkkkkOkkkOkkkkxxxxxdolcccclclooddl,.
        ,dxkxxxddolc:ccllodddxxxxxkkOkOOOOOOOOOOOOOOkkkkkkxxdlcclcccccc:'.
        .,oxxdooolccclooddxkkkkxxkkOOOOOOOOOOO0000OOOOOOOkkkdocccc::::,.
