about:
  firstName: Yuval
  lastName: Herziger
  nickname: Yuvi
  intro: |
    I'm A software engineer with over 8 years of diverse experience in a variety of fields and engineering paradigms;
    I believe in leading by example and constant learning; a certified AWS Solutions Architect Associate (SAA-C01) and
    Kubernetes Application Developer (CKAD).
    Off the grid, I'm a proud father, a loving partner to a psychology professor at the Technion, an amateur landscape
    and portrait photographer, and an okay guitar player.
    Born and raised in Israel, I just came back after having spent 7 years abroad. I lived in Cologne,
    Germany for 4 years and then moved to Columbus, Ohio, USA for another 3 years as an ex-pat.
  contact:
    emailAddress: yuvalhrz@gmail.com
  profiles:
    - name: GitHub
      url: https://www.github.com/yuvalherziger
    - name: LinkedIn
      url: https://www.linkedin.com/in/yuval-herziger-677b1531/
    - name: 500px
      url: https://500px.com/p/yuvalherziger?view=photos
    - name: Facebook
      url: https://www.facebook.com/herziger
  languages:
    - Hebrew  - native
    - English - proficient
    - German  - business (B1)
    - Spanish - basic
certifications:
  - name: AWS Solutions Architect Associate (SAA-C01)
    credentials: https://certmetrics.com/amazon/public/transcript.aspx?transcript=BFLC3C4C2JQ41J37
    expires: Jan 2023
experience:
  - companyName: Immuta Inc.
    companyWebsite: https://www.immuta.com
    location: Columbus, OH, USA
    roles:
    - name: Lead Software Engineer
      startDate: May 2020
      endDate: Jun 2021
      responsibilities:
        - Oversaw a team of 2 software engineers
        - Prioritize, plan, and execute ongoing development tasks across >= 10 codebases in an agile team
        - Provided deliverables to Immuta customers in the form of custom plugins and integrations
        - Supported deployments on-premises and private cloud environments
    - name: Software Engineer
      startDate: Aug 2018
      endDate: May 2020
      responsibilities:
        - Member of Immuta’s Applied Engineering team,
        - Designed and developed an identity manager that supported SAML 2.0 & OAuth 2.0/OIDC
        - Led technical POC’s with enterprise customers (some reaching $1m in ACV)
        - Assisted with HA and FT Kubernetes deployments on various infrastructures, primarily AWS and Azure
        - Developed and maintained various microservices
        - Provided assistance in various customer POC’s
        - Worked on a variety of distributed data computation systems such as EMR, Snowflake, and Databricks
        - Developed front-end components using Angular v{6, 7, 10}
  - companyName: Quintly GmbH
    companyWebsite: https://www.quintly.com
    location: Cologne, NRW, Germany
    roles:
    - name: Scrum Master
      startDate: Aug 2018
      endDate: May 2020
      responsibilities:
        - Led a team of 3 software engineers
        - |
          Estimated, planned, coordinated, and executed implementation of new features
    - name: Software Engineer
      startDate: Aug 2018
      endDate: May 2020
      responsibilities:
        - Implemented new features and maintain Quintly’s social media analytics product in a Scrum team
        - Developed back-end features using PHP, with utmost attention to design, architecture, and performance
        - Strong Emphasis on Domain-Driven Design (DDD) patterns
        - Developed front-end components using ReactJS and Redux
        - Experimented with Test-Driven Development (TDD) and wrote comprehensive unit and integration tests
        - Worked with MySQL, AWS DynamoDb and MongoDB databases
        - Studied and consumed from social media REST API's, often more than the docs could offer
education:
  - institute: Ruppin Academic Center
    degree: B.Sc. Industrial Engineering & Management
    major: Information Systems
    graduationDate: July 2013
    GPA: 3.3 (87%)
openSource:
  - projectName: Katch
    description: A Python library
    source: https://github.com/python-utils/katch
skills:
  - name: Python
    proficiency: 9
  - name: Angular
    proficiency: 9
  - name: Go
    proficiency: 7
  - name: Node.js (JS + TS)
    proficiency: 8
  - name: Docker
    proficiency: 9
  - name: Kubernetes
    proficiency: 8
  - name: Terraform
    proficiency: 4
  - name: AWS
    proficiency: 7
  - name: Azure
    proficiency: 5
  - name: PHP
    proficiency: 6
picture: |

  This is me:
                     .........   .................        .
                   ..................'''''''............
              ..  ...'..'''.......'',,;;;::;;,,'''........
              ......,;,',;;,,,,,;;;;cllllooooolll:;;;,'''...
          .....'',,,:cllllooooooooodxxxxxxxxxxdddolc:;;;;,'....
         ....'';c:cloodxxxxkkkkkkkkkkkkkkkkkkkxxxddolc:cc:;,....  .
        ...';,;cllodddxxkkkkkkOOOkOOOOOOOOOOOkkkkxxdolcccc:;,...
       ..',;:ccllloddxxkkkkOOOOOOOO0000000OOOOOkkkxdoollcc:;;'..
       ..;;;:clolooddxxkkOOOO00000000000000000OOkkxxdooolc:;,....
      ..,::;:clooddddxkkOO000KKKKKKKKKKKK000000OOkxxddoooc:;,'..  .
      ..,:::::loddddxxkOO000KKKKKKKKKKKKK000000OOkxxxddoolc:;;'.......
     ...,:::::ldddxxxkkkO00000KKKKKKKKKKKK00000OOkkkxxxddolcc:,.......
      ..';:::cldddxxxkkOOO00000KKKKKKKKK000000OOOkkkkkkxxdollc;'......
   .....';:::coodxxxkkkOOO000000000000000000OOOOOOkkkkkkxdolcc:,......
  .......;::ccoddxxkkkkOO0000000000000000000OOOOOOkkxdddoollcc:;.......
   ......,::cloodxkkkkkkkO000000000000000000000OOkxdlc;,,,,,;:c:,.....
   ......,::cclllollooddxk0000KKKKK00KKKKK0000Okxoc;,,,''....';c;.......
   ......;:::;,,,,,',;::coxkO0KKKKKKKKKKK0kxOko:;,'',:cccc;'..'::'...';.
   . ...';:;,.....'''.'''',;:ldkO00KKKKK0Oxoooc:clldxkkkxxdlc;,,:,. .;c'
  ...  .,::,'..';clodddocc::;;:lxO0000000Okdooolllc::;:cccllooo:;,..'cc.
   .'. .':;,;:clooolc:;;,;cclooodxO000000Oxooolldl'...'c:,;coxxoc;...ll.
   .,,..'::coollc,';;....;ooclodookO0000Okolodoodxc;;;cllccloxxdc;,..cl.
    ;l'.';:ldxolc::ll:;:coddoddoooxkO0OOkxolodxxxxxxxxxxxxxxxxxdl:;'.,;.
   .lo'.';:ldxxddxxxxxxkkkkxxdolodxkOOOOkxdoloddxkkOOOOOOOOOOkkdl:;'.,,.
   .cc..';:ldxkkkOOOkOOOOkkkxdoodddxkkkkkxdooodxkkkOOkkOkkOOkkkxoc,..;,
    ':'.';:ldxkOOOOOOOOkOOOkkxxdoddxxxkOkkddoodkkOOO00OOOOOOkkxdo:'.,:.
    .;:..,;ldxxkkOOOOOOO0000OkoloodxkOOOOkxdolldk000000000OOOkxdl:':l,
     .cc,.,codxxkkOO00000KK0kocloddxO000Okxddolcok0KKK00000OOkxdl;','
     .,lo;';lodxkOO00KKKKKKOdloxkkkk0KKKK0kxxkxdoxO0KKKK000Okxxol;.
       ':,.,:loxkOO0KKKKKK0Oxddddoodk0000kollloooxkO000K000Okxdlc,.
          .';codkkO0000000Okxdollccloddxdlccc:clodddxkkO00Okkxol:'.
          ..,:lodxOOOOkkxxddoclloolodxxxxooolcclccllllooxOOxxdoc;.
           .';cllokkdlllccclc:cclllodxkkxdolllllccc:;;::lxkdool:,.
            .':llldxdlc:;::cccloooooddddddooooolc:::::cllddlllc;..
             .,:lccxkxdollc:;:clooooddddddddoollc;:coddxkOxlloc,.
             .';cc:cxkkkxxdl:;:coooddooodxxxollccldxkkkkkxoclc;..
              .':c:;lxkkkxxxdooodxxkkkxxkkkkxddodxxxkkxxxoccc;'.
               .':c:;ldxxxdxxddddxxkkxxkkxxxxxxxxxkkxxdooc;:;'..
                ..;:;;:looodxxxxddddxxxxxxxxxxxkkkkxxdl:;;;;'.,,.
                 ..,;,,;cllodxxkkkxxxxddxxxkOOOkkxxddl:,,;;'.,::.
                 ...',,,;cloodxkkkkxxxddxxxkkOkkxdool:,,,'..';cc,.
                 .,...'',;cloddddxxxxkkxkkxkkkkxxdlc:,,,''.',:cc:.
                 .,,.....';:cloddxxxkOOkOkkxxxxxdol;,','''',;:ool:.
                 .;;,'.....';clodxxxxxxxxxxxdddol:;'',,''',,;coddl:'.
                 .::;,'''''..,;cloddooooooooolc:;,,,'',,,,,,;ldxxdoc;,...
                .;ll:,'',,,,,'',,;:;;;;::;,,;,'',,,,,;:;;;,,;cdxxxdolc:;;,'.
             ...,codl;'',;::::;;,,''''',''.',,,,;;;:cllc:;,,;:ldxkkxxddlccc;.
          ..'',:loddo:,,;:cc::cllc:::cc::;;;:::::cloooolc:;;;:cloxxxxkxxddo:.
        .,;:::coxxxdl:;;::cllcloooooddoooooollloloxxxxdoolc:::::clooxxkkkxl'
       .cloloodxkkxdc;;::cllloodxxxxkxxxxxxxxddxxxkkkxddddlcccc::cclodxxxd;.
       .lxxddxxxxxdl:::cclooodxxxxkkkkkxkkkkOkkkOkkkkxxxxxdolcccclclooddl,.
        ,dxkxxxddolc:ccllodddxxxxxkkOkOOOOOOOOOOOOOOkkkkkkxxdlcclcccccc:'.
        .,oxxdooolccclooddxkkkkxxkkOOOOOOOOOOO0000OOOOOOOkkkdocccc::::,.
          .:ddoolllclodddxxkOOOkkkkOOOOOOOOOO00000OOOOOOOkkxdoc::;;;,..
           .':clooooodxxxxxkOOOOOOOOOOOOOOOOOO000OOOOOkkxxxdolcc:;,..
             ..;clllloooddxkkkkkkOOOOOOOOOOOOOOOOOOOkxoodddolll:,..
                .';:::;:lloddxxkkkOkkkkkkkOOOOOOOOOOkxdddxdoc,..
